### ISSUE TITLE
docker-compose.vite.yaml: `version` is obsolete

### ISSUE THREAD

**Issue by estebancastro** [szenario-fordesigners/craft-vite-starter#121]
After run `ddev start`, there's a warning:

`time="2024-07-16T14:50:04-06:00" level=warning msg="/mysite/.ddev/docker-compose.vite.yaml: `version` is obsolete"`

It seems the version is not need it? https://github.com/docker/compose/issues/11628#issuecomment-2000072567

If you agree, you can remove the line 3 here: [https://github.com/szenario-fordesigners/craft-vite-starter/blob/main/patches/docker-compose.vite.yaml](https://github.com/szenario-fordesigners/craft-vite-starter/blob/main/patches/docker-compose.vite.yaml)

**Comment by smonist** [comment]
Removed in [713b574](https://github.com/szenario-fordesigners/craft-vite-starter/commit/713b5747ebba7721c504938c1fdf58e8696d3c68). Thanks for the notice :)

**Comment by smonist** [comment]
[Release 2.0.1](https://github.com/szenario-fordesigners/craft-vite-starter/releases/tag/2.0.1)
